/*
 * Copyright (C) 2024-2026 Lucas Cordiviola
 *
 * MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

// HERE you have to define your plug-in, company name, email and web
#define stringPluginName        "PulquiCrossover-2bands"

#define stringOriginalFilename  "PulquiCrossover-2bands.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription   "PulquiCrossover-2bands VST3 (64Bit)"
#else
#define stringFileDescription   "PulquiCrossover-2bands VST3"
#endif
#define stringCompanyWeb        "https://github.com/Lucarda"
#define stringCompanyEmail      "mailto:lucarda27@hotmail.com"
#define stringCompanyName       "Lucas Cordiviola"
#define stringLegalCopyright    "Copyright(c) 2025 Lucas Cordiviola."
#define stringLegalTrademarks   "VST is a trademark of Steinberg Media Technologies GmbH"
