/*
 * Copyright (C) 2024-2025 Lucas Cordiviola
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

// HERE you have to define your plug-in, company name, email and web
#define stringPluginName        "PulquiLimiter"

#define stringOriginalFilename  "PulquiLimiter.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription   "PulquiLimiter VST3 (64Bit)"
#else
#define stringFileDescription   "PulquiLimiter VST3"
#endif
#define stringCompanyWeb        "https://github.com/Lucarda"
#define stringCompanyEmail      "mailto:lucarda27@hotmail.com"
#define stringCompanyName       "Lucas Cordiviola"
#define stringLegalCopyright    "Copyright(c) 2024 Lucas Cordiviola."
#define stringLegalTrademarks   "VST is a trademark of Steinberg Media Technologies GmbH"
